version: '3.1'

services:
  bot:
    build: .
    image: dh/chatbot
    container_name: chatbot
    volumes:
      - ./data:/bot/data
      - ./src:/bot
    links:
      - db
    restart: always

  db:
    image: mariadb
    container_name: chatbot_db
    restart: always
    environment:
      MARIADB_USER: chatbot
      MARIADB_PASSWORD: example
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: Ranch
    volumes:
      - ./data-db:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306

