version: '3.1'

services:
  bot:
    build: .
    image: dh/chatbot
    container_name: chatbot
    volumes:
      - ./data:/bot/data
      - ./src:/bot
    links:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: chatbot
      MARIADB_PASSWORD: example
      MARIADB_ROOT_PASSWORD: examople
      MARIADB_DATABASE: Ranch
    volumes:
      - ./data-db:/var/lib/mysql


