version: '3.1'

services:
  bot:
    build: .
    image: dh/chatbot
    container_name: chatbot
    volumes:
      - ./data:/bot/data
    links:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: chatbot
      MARIADB_PASSWORD: example
      MARIADB_ROOT_PASSWORD: example_root
      MARIADB_DATABASE: Ranch
    volumes:
      - ./data-db:/var/lib/mysql


